2019-02-24 17:35:08,241 ERROR: Exception on /reset_password_request [POST] [in c:\users\celia\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\celia\microblog\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\celia\microblog\app\email.py", line 25, in send_password_reset_email
    user=user, token=token),
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 83, in _get_source_fast
    return loader.get_source(environment, template)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 43: invalid continuation byte
2019-02-24 17:47:39,627 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:52]
2019-02-24 17:58:27,912 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 17:59:33,492 ERROR: Exception on /reset_password_request [POST] [in c:\users\celia\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\celia\microblog\app\routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\celia\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token),
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\celia\microblog\venv\lib\site-packages\flask\templating.py", line 83, in _get_source_fast
    return loader.get_source(environment, template)
  File "c:\users\celia\microblog\venv\lib\site-packages\jinja2\loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 43: invalid continuation byte
2019-02-24 18:01:30,831 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:02:10,701 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:04:04,350 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:04:13,553 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:04:17,229 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:04:20,534 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 18:09:04,697 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:04:56,143 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:23:52,484 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:24:18,756 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:24:49,224 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:27:05,433 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:32:22,867 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
2019-02-24 19:33:46,760 INFO: Microblog startup [in C:\Users\celia\microblog\app\__init__.py:53]
